export const AUDIT_LOG = {
    Login: 'Logged In.',
    Logout: 'Logged Out.',
};

export const RESPONSE_MESSAGE = {
    STUDENT_GROUP_REPLACE: "Student replaced successfully",
    STUDENT_GROUP_ADDED: "Student added successfully",
    PROJECT_ENROLLED: "your group have been successfully enrolled to ",
    PROJECT_GOODLUCK: " Good Luck !!",
    CREATED: "Created successfully",
    MILESTONES_CREATED: "Milestones created successfully",
    MILESTONES_UPDATED: "Milestones updated successfully",
    MILESTONES_ENABLED: "Milestones enabled successfully",
    MILESTONES_DISABLED: "Milestones disabled successfully",
    ENROLLED_SUCCESSFULLY: "Enrolled successfully",
    ASSIGNED_SUCCESSFULLY: "Assigned successfully",
    CREATE_ASSIGNED_SUCCESSFULLY: "Created and assigned successfully",
    ASSIGNED_DUB: "Assigned successfully and duplicates found",
    UPDATED: "Updated successfully",
    UPLOADED: "Uploaded successfully",
    PROJECT_TRANSFERED: "Project Transferd successfully",
    DELETED: "Deleted successfully",
    REMOVED: "Removed successfully",
    GROUP_CREATED_SUCCESSFULLY: "Group created successfully",
    ENDORSED: "Endorsed successfully",
    SCHEDULED: "Scheduled Successfully",
    GROUP_CREATION_PROGRESS: "Group Creation is in progress, please wait",
    STUDENT_REMOVED: "Student has been removed",
    ATTENDANCES_SUCCESS: "Attendance's Marked successfully",
    ATTENDANCE_SUCCESS: "Attendance Marked successfully",
    COMMENT: "Commented successfully",
    SUBMIT:"Submited successfully"
}

export const ERROR_MESSAGES = {
    DUP_ENTRY: "Duplicate Entry",
    TRY_AGAIN: "Try again",
    NOT_FOUND: "Not found",
    USER_INACTIVE: "User inactive",
    USER_ALREADY_EXIST: "User already exists",
    PROJECT_NOT_FOUND: "Project not found",
    PS_NOT_FOUND: "Ps not found",
    MILESTONE_NOT_FOUND: "Milestone not found",
    MARKS_GIVEN_CANNOT_BE_CHANGED: "Marks given cannot be changed",
    MILESTONE_ALREADY_EXIST: "Milestones already exists",
    MILESTONES_ALREADY_EXIST: "Milestones already exists",
    MILESTONE_DESCRIPTION_NOT_FOUND: "Milestone description not found",
    GROUP_NOT_FOUND: "Group not found",
    USER_NOT_FOUND: "User not found",
    USER_NOT_FOUND_INACTIVE: "User not found or inactive",
    SERVER_ERROR: "Internal server error",
    RECORD_NOT_FOUND: "Record not found",
    BAD_REQUEST: "Bad request",
    FORBIDDEN_ACCESS: "Forbidden access",
    UNAUTHORIZED_ACCESS: "Unauthorized access",
    INVALID_CREDENTIALS: "Invalid credentials",
    ALREADY_EXISTS: "Already exists",
    NOT_EXISTS_INACTIVE: "not found or in inactive state",
    NOT_EXISTS_COMPLETED: "not found or In completed state",
    TOKEN_EXPIRE: "Token has expired",
    SESSION_EXPIRE: "Session has expired. Please login again.",
    MANY_REQUESTS: "Too many requests",
    GROUP_FORM_NOT_START: "Group formation has not started",
    MILESTONE_NOT_START: "Milestone uploading has not started",
    GROUP_FORM_END: "Group formation has ended",
    MILESTONE_END: "Milestone uploading has ended",
    MILESTONE_NOT_ENABLED: "Milestone uploading has not enabled",
    EVALUATION_UPLOAD_NOT_START: "Evaluation results upload not started yet",
    EVALUATION_UPLOAD_END: "Evaluation results uploading has ended",
    PROJECT_ENROLL_NOT_START: "Project enrollment has not started",
    PROJECT_ENROLL_END: "Project enrollment has ended",
    CANT_UPDATE: "Can't update because they are in a group",
    CANT_UPDATE_AFTER_ENDORSE: "Can't update after endorsement",
    ENDORSEMENT_NOT_START: "Endorsement has not started",
    ATTENDANCE_START_END: "Attendance can be marked after 10 a.m and before 6 p.m.",
    MAX_ENROLLMENTS: "Maximum enrollments exceeded for project",
    DIFF_COLLEGE: "Belongs to a different college",
    GROUP_ALREADY_ENROLLED_PROJECT: "Group already enrolled to project",
    GROUP_NOT_ENROLLED_PROJECT: "Group not enrolled to project",
    STUDENT_GROUP_EXISTS: "Students already exist in group",
    ALREADY_ENDORSED: "Already endorsed",
    MAKE_PS_INACTIVE: "Please make completed for previous academic year before creating new",
    GROUP_INACTIVE: "Please make students Inactive or move students to another group",
};
